version: '3.8'
services:
  php:
    build: .
    container_name: php-service
    volumes:
      - .:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 3001:80
    depends_on:
      - php-database

  php-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_TCP_PORT: 3306
    container_name: php-database
    restart: always

  php-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php-phpmyadmin
    environment:
      PMA_HOST: php-database
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 8080:80
    depends_on:
      - php-database